name: Master

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    uses: './.github/workflows/build.yml'
    secrets: inherit

  deploy:
    needs: [build]
    name: Deploy site
    uses: './.github/workflows/deploy.yml'
    secrets: inherit
