name: Pull Request

on:
  pull_request:

jobs:
  build:
    name: Build Pull Request
    uses: './.github/workflows/build.yml'
    secrets: inherit

  deploy:
    needs: [build]
    name: Deploy site
    uses: './.github/workflows/deploy.yml'
    secrets: inherit
