name: Verify

on:
  workflow_call:

jobs:
  audit:
    name: Build and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Audit
        run: npm audit

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
